# The file to use as input for the data
input_file: "excel_files/General_input_new_simple.xlsx"

# The file to output the results in
output_file: "output.txt"

parameters:
    BIG_M: 5000
    MAX_SOLAR_AREA: 500

# The solver to be used
solver:
    # the name of the solver
    name: "glpk"

    # The options to be passed to the solver
    options:
        mipgap: 0.05
